//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbContainer : DbContext
    {
        public dbContainer()
            : base("name=dbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblApplications> tblApplications { get; set; }
        public virtual DbSet<tblCrashReports> tblCrashReports { get; set; }
        public virtual DbSet<tblCustomers> tblCustomers { get; set; }
        public virtual DbSet<tblDevices> tblDevices { get; set; }
        public virtual DbSet<tblLanguageCodes> tblLanguageCodes { get; set; }
        public virtual DbSet<tblMessages> tblMessages { get; set; }
        public virtual DbSet<tblOperatingSystems> tblOperatingSystems { get; set; }
        public virtual DbSet<tblPhases> tblPhases { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    }
}
