//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessages
    {
        public int messageId { get; set; }
        public string message { get; set; }
        public int tblApplications_applicationId { get; set; }
        public int tbLanguageCodes_languageId { get; set; }
    
        public virtual tblApplications tblApplications { get; set; }
        public virtual tblLanguageCodes tblLanguageCodes { get; set; }
    }
}
