//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplications
    {
        public tblApplications()
        {
            this.tblDevices = new HashSet<tblDevices>();
            this.tblMessages = new HashSet<tblMessages>();
        }
    
        public int applicationId { get; set; }
        public string name { get; set; }
        public bool repeatable { get; set; }
        public string version { get; set; }
        public string uniqueId { get; set; }
        public string url { get; set; }
        public string repeatVersion { get; set; }
        public int tblOperatingSystems_operatingSystemId { get; set; }
        public int tblPhases_phaseId { get; set; }
    
        public virtual tblOperatingSystems tblOperatingSystems { get; set; }
        public virtual tblPhases tblPhases { get; set; }
        public virtual ICollection<tblDevices> tblDevices { get; set; }
        public virtual ICollection<tblMessages> tblMessages { get; set; }
    }
}
