//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblCustomers
    {
        public tblCustomers()
        {
            this.tblApplications = new HashSet<tblApplications>();
        }
    

        public int customerId { get; set; }
        [Required]
        [DisplayName("Contact Persoon")]
        public string contactPerson { get; set; }
        [Required]
        [DisplayName("Bedrijf")]
        public string companyName { get; set; }
        [Required]
        [DisplayName("Email addres")]
        [EmailAddress]
        public string email { get; set; }
        [Required]
        [DisplayName("Addres")]
        public string address { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual ICollection<tblApplications> tblApplications { get; set; }
    }
}
