//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDevices
    {
        public tblDevices()
        {
            this.tblCrashReports = new HashSet<tblCrashReports>();
        }
    
        public int deviceId { get; set; }
        public string operatingSystemVersion { get; set; }
        public string appVersion { get; set; }
        public string uniqueId { get; set; }
        public System.DateTime insertDate { get; set; }
        public System.DateTime lastCheckinDate { get; set; }
        public int tblApplications_applicationId { get; set; }
    
        public virtual tblApplications tblApplications { get; set; }
        public virtual ICollection<tblCrashReports> tblCrashReports { get; set; }
    }
}
