//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class tblLanguageCodes
    {
        public tblLanguageCodes()
        {
            this.tblMessages = new HashSet<tblMessages>();
        }
    
        public int languageId { get; set; }
        [DisplayName("Taal")]
        public string name { get; set; }
    
        public virtual ICollection<tblMessages> tblMessages { get; set; }
    }
}
