//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhases
    {
        public tblPhases()
        {
            this.tblApplications = new HashSet<tblApplications>();
        }
    
        public int phaseId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tblApplications> tblApplications { get; set; }
    }
}
